<template>
    <div class="nk-content ">
        <div class="container-fluid">
            <div class="nk-content-inner">
                <div class="nk-content-body">
                    <div class="nk-block-head nk-block-head-sm">
                        <div class="nk-block-between">
                            <div class="nk-block-head-content">
                                <h3 class="nk-block-title page-title">View Sale Bill</h3>
                            </div><!-- .nk-block-head-content -->
                        </div><!-- .nk-block-between -->
                    </div><!-- .nk-block-head -->
                    <div class="nk-block">
                        <div class="text-right">
                            <b> Generated By:</b>
                            <span> {{ generated_by }} </span>
                            <b class="ml-4"> Date Added:</b>
                            <span class="ml-3"> {{ date_added }} </span>
                        </div>
                        <div class="card card-bordered">
                            <div class="card-inner">
                                <div class="preview-block">
                                    <div class="row gy-4">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <p><b>Subject:</b> {{ subject }} </p>
                                            </div>
                                            <div class="form-group">
                                                <p><b>IUID:</b> {{ iuid }} </p>
                                            </div>
                                            <div class="form-group">
                                                <p><b>Customer:</b> {{ customer }} </p>
                                            </div>
                                            <div class="form-group">
                                                <p><b>Address:</b> {{ customer_address }} </p>
                                            </div>
                                            <div class="form-group">
                                                <p><b>Sale Bill For:</b> {{ iuid }} </p>
                                            </div>
                                            <div class="form-group">
                                                <p><b>Extra Attachment:</b> {{ iuid }} </p>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <p><b>Generated Date:</b> {{ generated_date }} </p>
                                            </div>
                                            <div class="form-group">
                                                <p><b>Sr No:</b> {{ sr_no }} </p>
                                            </div>
                                            <div class="form-group">
                                                <p><b>Supplier Invoice No:</b> {{ supplier_invoice_no }} </p>
                                            </div>
                                            <div class="form-group">
                                                <p><b>Product Main Category:</b> {{ product_category }} </p>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <p><b>Supplier:</b> {{ supplier }} </p>
                                            </div>
                                            <div class="form-group">
                                                <p><b>Bill Date:</b> {{ bill_date }} </p>
                                            </div>
                                            <div class="form-group">
                                                <p><b>Agent:</b> {{ agent }} </p>
                                            </div>
                                        </div>
                                    </div>
                                    <hr class="mt-5 mb-5">
                                    <div>
                                        <h6 class="mb-2">Item Details</h6>
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>Name</th>
                                                    <th>HSN</th>
                                                    <th>Pieces</th>
                                                    <th>Meters</th>
                                                    <th>Rate</th>
                                                    <th>Discount %</th>
                                                    <th>Discount Amt</th>
                                                    <th>CGST %</th>
                                                    <th>CGST Amt</th>
                                                    <th>SGST %</th>
                                                    <th>SGST Amt</th>
                                                    <th>IGST %</th>
                                                    <th>IGST Amt</th>
                                                    <th>Amount</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr v-for="(k, i) in itemDetails" :key="i">
                                                    <td> {{ k.item_name }} </td>
                                                    <td> {{ k.hsn }} </td>
                                                    <td> {{ k.pieces }} </td>
                                                    <td> {{ k.meters }} </td>
                                                    <td> {{ k.rate }} </td>
                                                    <td> {{ k.discount }} </td>
                                                    <td> {{ k.discount_amount }} </td>
                                                    <td> {{ k.cgst }} </td>
                                                    <td> {{ k.cgst_amount }} </td>
                                                    <td> {{ k.sgst }} </td>
                                                    <td> {{ k.sgst_amount }} </td>
                                                    <td> {{ k.igst }} </td>
                                                    <td> {{ k.igst_amount }} </td>
                                                    <td> {{ k.amount }} </td>
                                                </tr>
                                            </tbody>
                                            <tfoot style="border-top: 1px solid lightgray;">
                                                <tr>
                                                    <th></th>
                                                    <th>Total</th>
                                                    <th></th>
                                                    <th>{{ total_meters }}</th>
                                                    <th></th>
                                                    <th></th>
                                                    <th>{{ total_discount }}</th>
                                                    <th></th>
                                                    <th>{{ total_cgst }}</th>
                                                    <th></th>
                                                    <th>{{ total_sgst }}</th>
                                                    <th></th>
                                                    <th>{{ total_igst }}</th>
                                                    <th>{{ total_amount }}</th>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </div>
                                    <hr class="mt-5 mb-5">
                                    <div><h6 class="mb-3">Transport Details</h6></div>
                                    <div class="row gy-4">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <p><b>Transport:</b> {{ transport }} </p>
                                            </div>
                                            <div class="form-group">
                                                <p><b>LR/MR Date:</b> {{ lr_mr_date }} </p>
                                            </div>
                                            <div class="form-group">
                                                <p><b>Freight:</b> {{ freight }} </p>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <p><b>Station/To:</b> {{ station }} </p>
                                            </div>
                                            <div class="form-group">
                                                <p><b>Cases:</b> {{ cases }} </p>
                                            </div>
                                            <div class="form-group">
                                                <p><b>Change in Amount:</b> {{ change_in_amount }} </p>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <p><b>LR/MR No:</b> {{ lr_mr_no }} </p>
                                            </div>
                                            <div class="form-group">
                                                <p><b>Weight:</b> {{ weight }} </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <ViewCompanyDetails ref="company"></ViewCompanyDetails>
</template>
<script>
    import ViewCompanyDetails from '../../databank/companyComponents/modal/ViewCompanyDetailsModelComponent.vue';
    import $ from 'jquery';

    export default {
        name: 'viewSaleBill',
        props: {
            sale_bill_id: Number
        },
        components: {
            ViewCompanyDetails,
        },
        data() {
            return {
                generated_by: '',
                date_added: '',
                subject: '',
                iuid: '',
                customer: '',
                customer_address: '',
                supplier: '',
                sale_bill_for: '',
                extra_attachment: '',
                generated_date: '',
                sr_no: '',
                supplier_invoice_no: '',
                product_category: '',
                bill_date: '',
                agent: '',
                transport: '',
                lr_mr_date: '',
                lr_mr_no: '',
                freight: '',
                weight: '',
                station: '',
                cases: '',
                change_in_amount: '',
                itemDetails: [{
                    item_name: '',
                    hsn: '',
                    pieces: '',
                    meters: '',
                    rate: 0,
                    discount: 0,
                    discount_amount: 0,
                    cgst: 0,
                    cgst_amount: 0,
                    sgst: 0,
                    sgst_amount: 0,
                    igst: 0,
                    igst_amount: 0,
                    amount: 0,
                }],
                total_meters: 0,
                total_discount: 0,
                total_cgst: 0,
                total_sgst: 0,
                total_igst: 0,
                total_amount: 0,
                total_amount_words: '',
            }
        },
        created () {
            axios.get('/account/sale-bill/view-sale-bill-details/'+this.sale_bill_id)
            .then(response => {
                var data = response.data;
            });
        },
        methods: {
            showModal: function(id) {
                window.$('#overlay').show();
                this.$refs.company.fetch_company(id)
                window.$("#viewCompany1").modal('show');
                $('<div class="modal-backdrop fade show"></div>').appendTo(document.body);
                $('body').addClass('modal-open').css('overflow', 'hidden').css('padding-right', '17px');
            },
            closeModal: function() {
                window.$('#viewCompany1').modal('hide');
                $('.modal-backdrop').remove();
                $('body').removeClass('modal-open').removeAttr('style');
            }
        },
        mounted() {
            const self = this;
            /* const toINR = new Intl.NumberFormat('en-IN', {
                style: 'currency',
                currency: 'INR',
                // minimumFractionDigits: 2
            }); */
            var today = new Date();
            var dt = today.toJSON().slice(0, 10);
            var nDate = dt.slice(0, 4) + '-' + dt.slice(5, 7) + '-' + dt.slice(8, 10);
            $(document).on('click', '.delete-salebill', function(e) {
                if (confirm('Are you sure you want to delete?')) {
                    location.href = '/account/sale-bill/delete/' + $(this).attr('data-id');
                }
                return;
            });

            $(document).on('click', '.view-details', function(e) {
                self.showModal($(this).attr('data-id'));
            });
            document.getElementById('viewCompany1').addEventListener('hidden.bs.modal', function (event) {
                $('.modal-backdrop').remove();
            });
        },
    };
</script>

