<template>
    <div class="nk-content ">
        <div class="container-fluid">
            <div class="nk-content-inner">
                <div class="nk-content-body">
                    <div class="nk-block">
                        <div class="card card-bordered card-stretch">
                            <div class="card-header">
                                <div class="row">
                                    <div class="col-sm-4">
                                        <h3 class="nk-block-title page-title">Invoice List</h3>
                                    </div>
                                    <div class="col-md-8 text-right">

										<button @click="clearallfilter" class="btn btn-dark mx-1">
				                            Clear All
				                        </button>
                                        <a href="/account/commission/invoice/create-invoice" class="btn btn-icon btn-primary"><em class="icon ni ni-plus"></em></a>
				                    </div>
                                </div>

                            </div>
                            <div class="card-inner">
                                <div class="dataTables_filter row mt-2" id="invoice_filter"><input type="search" id="invoice_no" class="form-control form-control-sm mb-2 col-2" placeholder="Invoice No"> <input type="date" id="invoice_date" class="form-control form-control-sm col-2 mb-2" placeholder="Invoice Date" max="' + nDate +'"> <div class="input-group col-3 mb-2"><input type="text" id="company_name" class="form-control form-control-sm" placeholder="Company" ></div> <input type="search" id="agent_name" class="form-control form-control-sm col-2 mb-2" placeholder="Agent"> <input type="search" id="final_amount" class="form-control form-control-sm col-2" placeholder="Amount"> <select id="commission_status" class="form-control mx-2 col-2" placeholder="Comm. Status"><option value="" selected disabled>Comm. Status</option><option value="all">All</option><option value="none">None</option><option value="pending">Pending</option><option value="complete">Complete</option></select><select id="outward_status" class="form-control col-2" placeholder="Outward Status"><option value="" selected disabled>Outward Status</option><option value="all">All</option><option value="pending">Pending</option><option value="complete">Complete</option></select><input type="search" id="due_days" class="form-control form-control-sm col-2" placeholder="Due"><button class="form-control form-control-sm btn btn-primary mx-2 col-1" style="padding:1rem" id="filterinvoice">Filter</button></div>
                                <table id="invoiceTable" class="table table-hover table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Inv. No</th>
                                            <th>Inv. Date</th>
                                            <th>Gen. Date</th>
                                            <th>Company</th>
                                            <th>Agent</th>
                                            <th>Amount</th>
                                            <th>Comm. Status</th>
                                            <th>Outward Status</th>
                                            <th>Due</th>
                                            <th>Generated By</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div><!-- .card -->
                        </div>
                    </div><!-- .nk-block -->
                </div>
            </div>
        </div>
    </div>
    <ViewCompanyDetails ref="company"></ViewCompanyDetails>
</template>

<script>
    import ViewCompanyDetails from '../../databank/companyComponents/modal/ViewCompanyDetailsModelComponent.vue';

    import $ from 'jquery';
    import 'datatables.net-responsive-bs4/js/responsive.bootstrap4';
    import "datatables.net-buttons-bs5/js/buttons.bootstrap5";
    import 'pdfmake/build/pdfmake';
    import "datatables.net-buttons/js/buttons.html5";
    import "datatables.net-buttons/js/buttons.print";

    export default {
        name: 'Invoice',
        props: {
            excelAccess: Number,
        },
        components: {
            ViewCompanyDetails
        },
        data() {
            return {
            }
        },
        created() {
            axios.get('/account/commission/invoice/getinvoicesearch')
            .then(response => {
                $('#invoice_no').val(response.data.invoice_no);
                $('#invoice_date').val(response.data.invoice_date);
                $('#company_name').val(response.data.company_name);
                $('#agent_name').val(response.data.agent_name);
                $('#final_amount').val(response.data.final_amount);
                $('#commission_status').val(response.data.commission_status);
                $('#outward_status').val(response.data.outward_status);
                $('#due_days').val(response.data.due_days);
            });
        },
        methods: {
            showModal: function(id) {
                window.$('#overlay').show();
                this.$refs.company.fetch_company(id)
                window.$("#viewCompany1").modal('show');
                $('<div class="modal-backdrop fade show"></div>').appendTo(document.body);
                $('body').addClass('modal-open').css('overflow', 'hidden').css('padding-right', '17px');
            },
            closeModal: function() {
                window.$('#viewCompany1').modal('hide');
                $('.modal-backdrop').remove();
                $('body').removeClass('modal-open').removeAttr('style');
            },
            clearallfilter: function() {
                $("#invoice_filter").find('input, select').val("");
                $('#invoiceTable').DataTable().clear().draw();
            },
        },
        mounted() {
            const self = this;
            var dt_table = null;
            var today = new Date();
            var dt = today.toJSON().slice(0, 10);
            var nDate = dt.slice(0, 4) + '-' + dt.slice(5, 7) + '-' + dt.slice(8, 10);
            function init_dt_table () {
                dt_table = $('#invoiceTable').DataTable({
                    processing: true,
                    serverSide: true,
                    responsive: true,
                    ajax: {
                        url: "./invoice/list-data",
                        data: function (data) {
                            if ($('#invoice_no').val() == '') {
                                data.columns[0].search.value = '';
                            } else {
                                data.columns[0].search.value = $('#invoice_no').val();
                            }
                            if ($('#invoice_date').val() == '') {
                                data.columns[1].search.value = '';
                            } else {
                                data.columns[1].search.value = $('#invoice_date').val();
                            }
                            if ($('#company_name').val() == '') {
                                data.columns[3].search.value = '';
                            } else {
                                data.columns[3].search.value = $('#company_name').val();
                            }
                            if ($('#agent_name').val() == '') {
                                data.columns[4].search.value = '';
                            } else {
                                data.columns[4].search.value = $('#agent_name').val();
                            }
                            if ($('#final_amount').val() == '') {
                                data.columns[5].search.value = '';
                            } else {
                                data.columns[5].search.value = $('#final_amount').val();
                            }
                            if ($('#commission_status').val() == '') {
                                data.columns[6].search.value = '';
                            } else {
                                data.columns[6].search.value = $('#commission_status').val();
                            }
                            if ($('#outward_status').val() == '') {
                                data.columns[7].search.value = '';
                            } else {
                                data.columns[7].search.value = $('#outward_status').val();
                            }
                            if ($('#due_days').val() == '') {
                                data.columns[8].search.value = '';
                            } else {
                                data.columns[8].search.value = $('#due_days').val();
                            }
                        },
                        complete: function (data) { }
                    },
                    pagingType: 'full_numbers',
                    dom: 'Blrtip',
                    order: [[ 2, "desc" ]],
                    columns: [
                        { data: 'bill_no' },
                        { data: 'bill_date' },
                        { data: 'created_at' },
                        { data: 'company', orderable: false },
                        { data: 'agent_id', orderable: false },
                        // { data: 'total_payment_received_amount', render: $.fn.dataTable.render.number(',', '.', 0, '₹') },
                        { data: 'final_amount', render: $.fn.dataTable.render.number(',', '.', 0, '₹') },
                        { data: 'commission_status' },
                        { data: 'outward_status', orderable: false },
                        { data: 'due_days', orderable: false },
                        { data: 'generated_by', orderable: false },
                        { data: 'action', orderable: false },
                    ],
                    // search: {
                    //     return: true
                    // },
                    buttons: [{
                        extend: 'excelHtml5',
                        action: exportAllRecords,
                        exportOptions: {
                            columns: ':not(:last-child)'
                        }
                    }, {
                        extend: 'pdfHtml5',
                        action: exportAllRecords,
                        exportOptions: {
                            columns: ':not(:last-child)'
                        }
                    },
                    'print'],
                    // createdRow: function( row, data, dataIndex ) {
                    // }
                })
                .on( 'init.dt', function () {
                    $('').insertAfter('.dataTables_length');
                    axios.get('/common/list-all-companies')
                        .then(response => {
                            new Autocomplete(document.getElementById('company_name'), {
                                threshold: 2,
                                data: response.data,
                                maximumItems: 5,
                                label: 'name',
                                value: 'id',
                                onSelectItem: ({ label, value }) => { }
                            });
                        });
                    setTimeout(() => {
                        $('#company_name').siblings('div.dropdown-menu').on('click', '.dropdown-item', function (e) {
                            dt_table.clear().draw();
                        });
                    }, 1000);
                } );
                dt_table.on( 'responsive-resize', function ( e, datatable, columns ) {
                    var count = columns.reduce( function (a,b) {
                        return b === false ? a+1 : a;
                    }, 0 );
                } );
            }
            init_dt_table();
            function exportAllRecords(e, dt, button, config) {
                var self = this;
                var oldStart = dt.settings()[0]._iDisplayStart;
                dt.one('preXhr', function (e, s, data) {
                    // Just this once, load all data from the server...
                    data.start = 0;
                    data.length = 'all';
                    dt.one('preDraw', function (e, settings) {
                        // Call the original action function
                        if (button[0].className.indexOf('buttons-excel') >= 0) {
                            $.fn.dataTable.ext.buttons.excelHtml5.available(dt, config) ?
                                $.fn.dataTable.ext.buttons.excelHtml5.action.call(self, e, dt, button, config) :
                                $.fn.dataTable.ext.buttons.excelFlash.action.call(self, e, dt, button, config);
                        } else if (button[0].className.indexOf('buttons-pdf') >= 0) {
                                $.fn.dataTable.ext.buttons.pdfHtml5.available(dt, config) ?
                                $.fn.dataTable.ext.buttons.pdfHtml5.action.call(self, e, dt, button, config) :
                                $.fn.dataTable.ext.buttons.pdfFlash.action.call(self, e, dt, button, config);
                        }
                        dt.one('preXhr', function (e, s, data) {
                            // DataTables thinks the first item displayed is index 0, but we're not drawing that.
                            // Set the property to what it was before exporting.
                            settings._iDisplayStart = oldStart;
                            data.start = oldStart;
                        });
                        // Reload the grid with the original page. Otherwise, API functions like table.cell(this) don't work properly.
                        setTimeout(dt.ajax.reload, 10);
                        // Prevent rendering of the full data to the DOM
                        return false;
                    });
                });
                // Requery the server with the new one-time export settings
                dt.ajax.reload();
            }
            var draw = 1;
            // $(document).on('keyup', '#invoice_filter input', function(e) {
            //     if ($(this).val() == '') {
            //         if (draw == 0) {
            //             dt_table.clear().draw();
            //             draw = 1;
            //         }
            //     } else {
            //         if (e.keyCode == 13) {
            //             dt_table.clear().draw();
            //         }
            //         draw = 0;
            //     }
            // });
            // $(document).on('change', '#invoice_filter select', function(e) {
            //     if ($(this).val() == '') {
            //         if (draw == 0) {
            //             dt_table.clear().draw();
            //             draw = 1;
            //         }
            //     } else {
            //         dt_table.clear().draw();
            //         draw = 0;
            //     }
            // });
            /* window.addEventListener('load', function () {
                axios.get('/common/list-all-companies')
                .then(response => {
                    new Autocomplete(document.getElementById('company_name'), {
                        threshold: 2,
                        data: response.data,
                        maximumItems: 5,
                        label: 'name',
                        value: 'id',
                        onSelectItem: ({ label, value }) => { }
                    });
                });
                setTimeout(() => {
                    $('#company_name').siblings('div.dropdown-menu').on('click', '.dropdown-item', function (e) {
                        dt_table.clear().draw();
                    });
                }, 1000);
            }, false); */

            $(document).on('click', '.delete-invoice', function(e) {
                if (confirm('Are you sure you want to delete?')) {
                    location.href = '/account/commission/invoice/delete/' + $(this).attr('data-id');
                }
                return;
            });

            $(document).on('click', '#filterinvoice', function(e) {
                axios.post('/account/commission/invoice/storeinvoicesearch', {
                    invoice_no : $('#invoice_no').val(),
                    invoice_date : $('#invoice_date').val(),
                    company_name : $('#company_name').val(),
                    agent_name : $('#agent_name').val(),
                    final_amount : $('#final_amount').val(),
                    commission_status : $('#commission_status').val(),
                    outward_status : $('#outward_status').val(),
                    due_days : $('#due_days').val()
                })
            .then(response => {
                
            });
                $('#invoiceTable').DataTable().draw();
            });

            $(document).on('click', '.view-details', function(e) {
                self.showModal($(this).attr('data-id'));
            });
            document.getElementById('viewCompany1').addEventListener('hidden.bs.modal', function (event) {
                $('.modal-backdrop').remove();
            });

        },
    };
</script>

<style scoped>
    .icon.ni.ni-alert-fill, .icon.ni.ni-check-thick {
        font-size: 20px;
    }
</style>
