<template>
<div id="viewCompany">
<div v-for="(companyList, index) in companyList" :key="index">
    <div class="modal fade" :id="(companyList.company_name)">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <table class = "datatable-init-export nowrap">
                        <tr>
                            <td rowspan="3">
                                <h5 class="modal-title">Company Details</h5>
                            </td>
                            <td style="text-align: right; padding-left:390px;">
                                <b>Generated By:</b> B Vikas Chandra <b>Date Added:</b> 04/02/2022
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align: right;">
                                <b>Updated By:</b> B Vikas Chandra <b>Date Updated:</b> 04/02/2022
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align: right;">
                                <b>Verified By:</b> B Vikas Chandra <b>Date Verified:</b> 04/02/2022
                            </td>
                        </tr>
                    </table>
                    <a href="#" class="close" data-dismiss="modal" aria-label="Close">
                        <em class="icon ni ni-cross"></em>
                    </a>
                </div>
                <div class="nk-block">
                        <div class="card card-bordered card-stretch">
                            <div class="card-inner">
                                <table class="datatable-init-export nowrap table" data-export-title="Export">
                                    <tr>
                                        <td class="table_border"><b>Link Companies</b></td>
                                        <td class="table_border1">{{companyList.id}}</td>
                                    </tr>
                                    <tr>
                                        <td class="table_border"><b>Company Name</b></td>
                                        <td class="table_border1">{{companyList.company_name}}</td>
                                    </tr>
                                    <tr>
                                        <td class="table_border"><b>Company Type</b></td>
                                        <td class="table_border1">{{companyList.company_type}}</td>
                                    </tr>
                                    <tr>
                                        <td><b>GST No</b></td>
                                        <div v-for="(packagingDetails, index) in packagingDetails" :key="index">
                                        <td v-if="(packagingDetails.company_id) == (companyList.id)">{{packagingDetails.gst_no}}</td>
                                        </div>
                                    </tr>
                                </table>
                            </div><!-- .card -->
                        </div>
                    </div><!-- .nk-block -->
                    <div class="modal-header">
                        <h6 class="modal-title"> Contact Details</h6>
                    </div>
                    <div class="nk-block">
                        <div class="card card-bordered card-stretch">
                            <div class="card-inner">
                                <table class="datatable-init-export nowrap table" data-export-title="Export">
                                                <thead>
                                                    <tr>
                                                        <th>Name</th>
                                                        <th>Designation</th>
                                                        <th>Mobile</th>
                                                        <th>Email Id</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr v-for="(multipleAddress, index) in multipleAddress" :key="index">
                                                        <td v-if="(multipleAddress.company_id) == (companyList.id)">{{ multipleAddress.name }}</td>
                                                        <td v-if="(multipleAddress.company_id) == (companyList.id)">{{ multipleAddress.designation_name }}</td>
                                                        <td v-if="(multipleAddress.company_id) == (companyList.id)">{{ multipleAddress.mobile }}</td>
                                                        <td v-if="(multipleAddress.company_id) == (companyList.id)">{{ multipleAddress.email }}</td>
                                                    </tr>
                                                    <tr v-for="(companyContactDetails, index) in companyContactDetails" :key="index">
                                                        <td v-if="(companyContactDetails.company_id) == (companyList.id)">{{ companyContactDetails.contact_person_name }}</td>
                                                        <td v-if="(companyContactDetails.company_id) == (companyList.id)">{{ companyContactDetails.name }}</td>
                                                        <td v-if="(companyContactDetails.company_id) == (companyList.id)">{{ companyContactDetails.contact_person_mobile }}</td>
                                                        <td v-if="(companyContactDetails.company_id) == (companyList.id)">{{ companyContactDetails.contact_person_email }}</td>
                                                    </tr>
                                                </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="modal-header">
                        <h6 class="modal-title">Multiple Addresses</h6>
                    </div>
                    <div class="nk-block">
                        <div class="card card-bordered card-stretch">
                            <div class="card-inner">
                                <table class="datatable-init-export nowrap table" data-export-title="Export">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th>Type of Address</th>
                                            <th>Address</th>
                                            <th>Land Line Number</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr v-for="(companyAddress, index) in companyAddress" :key="index">
                                            <td><em class="icon ni ni-plus"></em></td>
                                            <td v-if="(companyAddress.company_id) == (companyList.id)">{{ companyAddress.name }}</td>
                                            <td v-if="(companyAddress.company_id) == (companyList.id)">{{ companyAddress.address }}</td>
                                            <td v-if="(companyAddress.company_id) == (companyList.id)">{{ companyAddress.mobile }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                        <div class="card card-bordered card-stretch">
                            <div class="card-inner">
                                <table class="datatable-init-export nowrap bor_table" data-export-title="Export">
                                    <tr>
                                        <td><b>Main City</b></td>
                                        <div v-for="(companyCity, index) in companyCity" :key="index">
                                        <td v-if="(companyList.company_city) == (companyCity.id)">{{companyCity.name}}</td>
                                        </div>
                                    </tr>
                                    <tr>
                                        <td class="table_border"><b>Website</b></td>
                                        <td class="table_border1">{{companyList.company_website}}</td>
                                    </tr>
                                    <tr>
                                        <td><b>Multiple Emails</b></td>
                                        <div v-for="(multipleEmails, index) in multipleEmails" :key="index">
                                        <td v-if="(multipleEmails.company_id) == (companyCity.id)">{{ multipleEmails.email_id }}</td>
                                        </div>
                                    </tr>
                                    <tr>
                                        <td class="table_border"><b>Email Id</b></td>
                                        <td  class="table_border1"></td>
                                    </tr>
                                    <tr>
                                        <td><b>Landline No</b></td>
                                        <td>{{companyList.company_mobile}}</td>
                                    </tr>
                                    <tr>
                                        <td><b>Mobile No</b></td>
                                        <td>{{companyList.company_landline}}</td>
                                    </tr>
                                    <tr>
                                        <td><b>Watchout</b></td>
                                        <td>{{companyList.company_watchout}}</td>
                                    </tr>
                                    <tr>
                                        <td><b>Remarks Watchout</b></td>
                                        <td>{{companyList.company_remark_watchout}}</td>
                                    </tr>
                                    <tr>
                                        <td class="table_border"><b>About Company</b></td>
                                        <td class="table_border1">{{companyList.company_about}}</td>
                                    </tr>
                                    <tr>
                                        <td><b>Company</b></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td class="table_border"><b>Category</b></td>
                                        <td class="table_border1"></td>
                                    </tr>
                                </table>
                            </div><!-- .card -->
                        </div>
            </div>
        </div>
    </div>
</div>
</div>
</template>
<script>
var company =[];
export default{
    name: 'companyList',
    components: {
        },
    data(){
        return {
                companyList: [],
                companyCity: [],
                companyAddress:[],
                companyContactDetails:[],
                multipleEmails:[],
                packagingDetails:[],
                multipleAddress:[]
            }
    },
    watch:{

    },
    created(){
        axios.get('./reference/companylist')
            .then(response => {
                company = response.data;
                this.companyList = company.companyList;
                this.companyCity = company.companyCity;
                this.companyAddress = company.companyAddress;
                this.companyContactDetails = company.companyContactDetails;
                this.multipleEmails = company.multipleEmails;
                this.packagingDetails = company.packagingDetails;
                this.multipleAddress = company.multipleAddress;
                console.log(this.multipleAddress = company.multipleAddress);
            });
    },
    methods:{
        },
    mounted(){
        console.log("This is about Component");
    },
}
</script>

<style>
    #viewCompany .modal-dialog {
        max-width: 1000px;
    }
    /* th, td {
  border-style: hidden;
    } */
    .bor_table{
        width: 100%; margin-bottom: 1rem; color: #526484;
    }
    .bor_table th, .bor_table td { padding: 0.1rem; vertical-align: top; }
    .table_border {
        width:20%;
       border-bottom: 2px dotted #ddd;
    }
    .table_border1 {
       border-bottom: 2px dotted #ddd;
    }
</style>
