<template>
    <div class="nk-content ">
        <div class="container-fluid">
            <div class="nk-content-inner">
                <div class="nk-content-body">
                    <div class="nk-block">
                        <div class="card card-bordered card-stretch">
                            <div class="card-header">
                                <div class="row">
                                    <div class="col-sm-4">
                                        <h3 class="nk-block-title page-title">Register Lists</h3>
                                    </div>
                                    <div class="col-md-8 text-right">
                                        <a v-bind:href="create_outward" class="dropdown-toggle btn btn-icon btn-primary pr-2"><em class="icon ni ni-plus"></em> Outward</a>
                                        <a v-bind:href="create_inward" class="dropdown-toggle btn btn-icon btn-primary pr-2 mx-2"><em class="icon ni ni-plus"></em> Inward</a>
                                        <button @click="clearallfilter" class="btn btn-dark px-2">Clear</button>
				                    </div>
                                </div>

                            </div>
                            <div class="card-inner table-responsive">
                                <table class="table table-hover" id="register">
                                    <thead>
                                        <tr>
                                            <th>IUID</th>
                                            <th>OUID</th>
                                            <th>Reference No</th>
                                            <th>Date / Time </th>
                                            <th>Time Completed</th>
                                            <th>IO Type</th>
                                            <th>IO Medium</th>
                                            <th>IO Details</th>
                                            <th>Company</th>
                                            <th>Supplier</th>
                                            <th>Cmp type</th>
                                            <th>Generated By</th>
                                            <th>Assign To</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div><!-- .card -->
                        </div>
                    </div><!-- .nk-block -->
                </div>
            </div>
        </div>
    </div>
    <ViewCompanyDetails ref="company"></ViewCompanyDetails>
</template>

<script>
    import ViewCompanyDetails from '../databank/companyComponents/modal/ViewCompanyDetailsModelComponent.vue';
    import 'jquery/dist/jquery.min.js';
    import 'datatables.net-bs5/js/dataTables.bootstrap5';
    import 'datatables.net-responsive-bs4/js/responsive.bootstrap4';
    import "datatables.net-buttons-bs5/js/buttons.bootstrap5";
    import "datatables.net-buttons/js/buttons.flash.js";
    import "datatables.net-buttons/js/buttons.html5.js";
    import "datatables.net-buttons/js/buttons.print.js";
    import $ from 'jquery';


    export default {
        name: 'companyCategory',
        props: {
            excelAccess: Number,
        },
        components: {
            ViewCompanyDetails
        },
        data() {
            return {
                create_inward: '/register/inward/sample',
                create_outward: '/register/create-outward',
            }
        },
        methods: {
            showModal: function(id) {
                window.$('#overlay').show();
                this.$refs.company.fetch_company(id)
                window.$("#viewCompany1").modal('show');
                $('<div class="modal-backdrop fade show"></div>').appendTo(document.body);
                $('body').addClass('modal-open').css('overflow', 'hidden').css('padding-right', '17px');
            },
            closeModal: function() {
                window.$('#viewCompany1').modal('hide');
                $('.modal-backdrop').remove();
                $('body').removeClass('modal-open').removeAttr('style');
            },
            clearallfilter(event) {
                $('#register_filter').find("input[type=search]").val('');
                $('#register_filter').find("input[type=date]").val('');
                $('#register').DataTable().clear().draw();
            },
        },
        mounted() {
            const self = this;
            var buttons = [];
            var dt_table = null;
            if(this.excelAccess == 1) {
                buttons = [{
                    extend: 'excelHtml5',
                    action: exportAllRecords,
                    exportOptions: {
                        columns: ':not(:last-child)'
                    }
                }, {
                    extend: 'pdfHtml5',
                    action: exportAllRecords,
                    exportOptions: {
                        columns: ':not(:last-child)'
                    }
                },
                'print'];
            }
            function init_dt_table () {
                dt_table = $('#register').DataTable({
                    processing: true,
                    serverSide: true,
                    lengthChange: true,
                    ajax: {
                        url: "/register/list",
                        data: function (data) {
                            if ($('#iuid').val() == '') {
                                data.columns[0].search.value = '';
                            } else {
                                data.columns[0].search.value = $('#iuid').val();
                            }
                            if ($('#ouid').val() == '') {
                                data.columns[1].search.value = '';
                            } else {
                                data.columns[1].search.value = $('#ouid').val();
                            }
                            if ($('#ref_no').val() == '') {
                                data.columns[2].search.value = '';
                            } else {
                                data.columns[2].search.value = $('#ref_no').val();
                            }
                            if ($('#date_added').val() == '') {
                                data.columns[3].search.value = '';
                            } else {
                                data.columns[3].search.value = $('#date_added').val();
                            }
                            if ($('#iotype').val() == '') {
                                data.columns[4].search.value = '';
                            } else {
                                data.columns[4].search.value = $('#iotype').val();
                            }
                            if ($('#iomedium').val() == '') {
                                data.columns[5].search.value = '';
                            } else {
                                data.columns[5].search.value = $('#iomedium').val();
                            }
                            if ($('#company').val() == '') {
                                data.columns[6].search.value = '';
                            } else {
                                data.columns[6].search.value = $('#company').val();
                            }
                            if ($('#supplier').val() == '') {
                                data.columns[7].search.value = '';
                            } else {
                                data.columns[7].search.value = $('#supplier').val();
                            }
                            if ($('#cmptype').val() == '') {
                                data.columns[8].search.value = '';
                            } else {
                                data.columns[8].search.value = $('#cmptype').val();
                            }
                            if ($('#generatedby').val() == '') {
                                data.columns[9].search.value = '';
                            } else {
                                data.columns[9].search.value = $('#generatedby').val();
                            }
                            if ($('#assignto').val() == '') {
                                data.columns[10].search.value = '';
                            } else {
                                data.columns[10].search.value = $('#assignto').val();
                            }
                        },
                        complete: function (data) { }
                    },
                    pagingType: 'full_numbers',
                    dom: "Blrtip",
                    order: [[3, "desc"]],
                    columns: [
                        { data: 'iuid' },
                        { data: 'ouid' },
                        { data: 'reference_id'},
                        { data: 'created_at'},
                        { data: 'timecompleted', orderable: false },
                        { data: 'iotype', orderable: false},
                        { data: 'iomedium', orderable: false },
                        { data: 'iodetail', orderable: false},
                        { data: 'company', orderable: false},
                        { data: 'supplier', orderable: false},
                        { data: 'cmptype', orderable: false },
                        { data: 'genby', orderable: false },
                        { data: 'assignto', orderable: false},
                        { data: 'action', orderable: false},
                    ],
                    search: {
                        return: true
                    },
                    buttons: buttons,
                    "fnRowCallback": function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {
                        switch(aData['iotype']){
                            case "Outward Commission Invoice":
                                $('td', nRow).css('background-color', '#C4FFC4')
                                break;
                        }
                        switch(aData['color_flag']){
                            case 1:
                                $('td', nRow).css('background-color', '#FFFFC8')
                                break;
                            case 2:
                                $('td', nRow).css('background-color', '#F2DEDE')
                                break;
                            case 3:
                                $('td', nRow).css('background-color', '#C4FFC4')
                                break;

                        }
                    }

                })
                .on( 'init.dt', function () {
                    $('<div class="dataTables_filter mt-2" id="register_filter"><input type="search" id="iuid" class="form-control form-control-sm" placeholder="iuid"><input type="search" id="ouid" class="form-control form-control-sm" placeholder="ouid"><input type="search" id="ref_no" class="form-control form-control-sm" placeholder="Reference No"><input type="date" id="date_added" class="form-control form-control-sm" placeholder="Date Added"><input type="search" id="iotype" class="form-control form-control-sm" placeholder="IO Type"><input type="search" id="iomedium" class="form-control form-control-sm" placeholder="IO Medium"><input type="search" id="company" class="form-control form-control-sm" placeholder="Company"><input type="search" id="supplier" class="form-control form-control-sm" placeholder="Supplier Name"><input type="search" id="cmptype" class="form-control form-control-sm" placeholder="CMP type"><input type="search" id="generatedby" class="form-control form-control-sm" placeholder="Generate By"><input type="search" id="assignto" class="form-control form-control-sm" placeholder="Assign to"></div>').insertAfter('.dataTables_length');
                });
            }
            init_dt_table();
            function exportAllRecords(e, dt, button, config) {
                var self = this;
                var oldStart = dt.settings()[0]._iDisplayStart;
                dt.one('preXhr', function (e, s, data) {
                    // Just this once, load all data from the server...
                    data.start = 0;
                    data.length = 'all';
                    dt.one('preDraw', function (e, settings) {
                        // Call the original action function
                        if (button[0].className.indexOf('buttons-excel') >= 0) {
                            $.fn.dataTable.ext.buttons.excelHtml5.available(dt, config) ?
                                $.fn.dataTable.ext.buttons.excelHtml5.action.call(self, e, dt, button, config) :
                                $.fn.dataTable.ext.buttons.excelFlash.action.call(self, e, dt, button, config);
                        } else if (button[0].className.indexOf('buttons-pdf') >= 0) {
                                $.fn.dataTable.ext.buttons.pdfHtml5.available(dt, config) ?
                                $.fn.dataTable.ext.buttons.pdfHtml5.action.call(self, e, dt, button, config) :
                                $.fn.dataTable.ext.buttons.pdfFlash.action.call(self, e, dt, button, config);
                        }
                        dt.one('preXhr', function (e, s, data) {
                            // DataTables thinks the first item displayed is index 0, but we're not drawing that.
                            // Set the property to what it was before exporting.
                            settings._iDisplayStart = oldStart;
                            data.start = oldStart;
                        });
                        // Reload the grid with the original page. Otherwise, API functions like table.cell(this) don't work properly.
                        setTimeout(dt.ajax.reload, 10);
                        // Prevent rendering of the full data to the DOM
                        return false;
                    });
                });
                // Requery the server with the new one-time export settings
                dt.ajax.reload();
            }
            var draw = 1;
            $(document).on('keyup', '#register_filter input', function(e) {
                 if ($(this).val() == '') {
                    if (draw == 0) {
                        dt_table.clear().draw();
                        draw = 1;
                    }
                } else {
                    if (e.keyCode == 13) {
                        dt_table.clear().draw();
                    }
                    draw = 0;
                }
            });

            $(document).on('click', '.view-details', function(e) {
                self.showModal($(this).attr('data-id'));
            });
            document.getElementById('viewCompany1').addEventListener('hidden.bs.modal', function (event) {
                $('.modal-backdrop').remove();
            });
        },
    };
</script>
<style>
</style>
