<template>
    <div class="nk-content ">
        <div class="container-fluid">
            <div class="nk-content-inner">
                <div class="nk-content-body">
                    <div class="nk-block-head nk-block-head-sm">
                        <div class="nk-block-between">
                            <div class="nk-block-head-content">
                                <h3 class="nk-block-title page-title">Reference Details</h3>
                            </div><!-- .nk-block-head-content -->
                        </div><!-- .nk-block-between -->
                    </div><!-- .nk-block-head -->
                    <div class="nk-block">
                        <div class="card card-bordered">
                            <div class="card-inner">
                                    <div class="preview-block">
                                        <div class="row gy-4">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="form-label" for="fv-first-name">Reference ID :</label> {{ referenceID.reference_id }}
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row gy-4">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="form-label" for="fv-first-name">Receive Date :</label> {{ referenceID.selection_date }}
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row gy-4">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="form-label" for="fv-first-name">Generated By :</label> {{ user.username }}
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row gy-4">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="form-label" for="fv-first-name">In / Out :</label> <span v-if="referenceID.inward_or_outward == '1'" class="data-value">Inward</span>
                                                    <span v-if="referenceID.inward_or_outward == '0'" class="data-value">Outward</span>
                                                    <!-- <label class="form-label" for="fv-first-name">In / Out :</label> Inward -->
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row gy-4">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="form-label" for="fv-first-name">Type :</label> {{ referenceID.type_of_inward }}
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row gy-4">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="form-label" for="fv-first-name">Company :</label> {{ company.company_name }}
                                                </div>
                                            </div>
                                        </div>

                                        <!-- By hand & Inward -->

                                        <div v-if="referenceID.type_of_inward == 'Hand' && referenceID.inward_or_outward == '1'">
                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">From Name :</label> {{ referenceID.from_name }}
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">Weight Of Parcel :</label> {{ referenceID.weight_of_parcel }}
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">Received Date :</label> {{ referenceID.courier_received_time }}
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">Delivery By :</label> {{ referenceID.delivery_by }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <!-- By hand & Outward -->

                                        <div v-if="referenceID.type_of_inward == 'Hand' && referenceID.inward_or_outward == '0'">
                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">To Name :</label>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">Weight Of Parcel :</label> {{ referenceID.weight_of_parcel }}
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">Delivery By :</label> {{ referenceID.delivery_by }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <!-- By Courier & Inward -->

                                        <div v-if="referenceID.type_of_inward == 'Courier' && referenceID.inward_or_outward == '1'">
                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">From Name :</label> {{ referenceID.from_name }}
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">Courrier Name :</label> {{ referenceID.courier_name }}
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">Courrier Receipt No :</label> {{ referenceID.courier_receipt_no }}
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">Weight Of Parcel :</label> {{ referenceID.weight_of_parcel }}
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">Received Date :</label> {{ referenceID.courier_received_time }}
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">Delivery By :</label> {{ referenceID.delivery_by }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <!-- By Email & Inward -->

                                        <div v-if="referenceID.type_of_inward == 'Email' && referenceID.inward_or_outward == '1'">
                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">From Email :</label> {{ referenceID.from_email_id }}
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">Receiver Email :</label> {{ referenceID.receiver_email_id }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <!-- By Email & Outward -->

                                        <div v-if="referenceID.type_of_inward == 'Email' && referenceID.inward_or_outward == '0'">
                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">To Name :</label> {{ referenceID.from_name }}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">From Email :</label> {{ referenceID.from_email_id }}
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">Receiver Email :</label> {{ referenceID.receiver_email_id }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <!-- By Message & Inward -->
                                        <div v-if="referenceID.type_of_inward == 'Message' || referenceID.Reference_via == 'Message' || referenceID.Reference_via == 'Whatsapp' && referenceID.inward_or_outward == '1'">
                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">From Name :</label> {{ referenceID.from_name }}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">From Number :</label> {{ referenceID.from_number }}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">Receiver Number :</label> {{ referenceID.receiver_number }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <!-- By Message & Outward -->
                                        <div v-if="referenceID.type_of_inward == 'Message' || referenceID.Reference_via == 'Message' || referenceID.Reference_via == 'Whatsapp' && referenceID.inward_or_outward == '0'">
                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">To Name :</label> {{ referenceID.from_name }}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">From Number :</label> {{ referenceID.from_number }}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row gy-4">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label class="form-label" for="fv-first-name">Receiver Number :</label> {{ referenceID.receiver_number }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                        </div><!-- .card -->
                    </div><!-- .nk-block -->
                     <div class="nk-block-head nk-block-head-sm">
                        <div class="nk-block-between">
                            <div class="nk-block-head-content">
                                <h3 class="nk-block-title page-title">List of Reference Details (Reference Id: {{ referenceID.reference_id }})</h3>
                            </div><!-- .nk-block-head-content -->
                        </div><!-- .nk-block-between -->
                    </div><!-- .nk-block-head -->
                    <div class="nk-block">
                        <div class="card card-bordered card-stretch">
                            <div class="card-inner">
                                <table class="datatable-init-export nowrap table" data-export-title="Export">
                                    <thead>
                                        <tr>
                                            <th>IUID</th>
                                            <th>OUID</th>
                                            <th>Date / Time</th>
                                            <th>Type</th>
                                            <th>Ref. Via</th>
                                            <th>Followup Via</th>
                                            <th>Subject</th>
                                            <th>Company</th>
                                            <th>Genrated by</th>
                                            <th>Assigned to</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr v-if="inward_outward.inward_or_outward == '1'">
                                            <td>{{inward_outward.iuid}}</td>
                                            <td>-</td>
                                            <td>{{ inward_outward.selection_date }}</td>
                                            <td v-if="inward_outward.system_module_id == '1'">Enquiry</td>
                                            <td v-else-if="inward_outward.system_module_id == '2'">Order</td>
                                            <td v-else-if="inward_outward.system_module_id == '3'">Complain</td>
                                            <td v-else-if="inward_outward.system_module_id == '4'">General</td>
                                            <td v-else-if="inward_outward.system_module_id == '5'">Sale Bill</td>
                                            <td v-else-if="inward_outward.system_module_id == '6'">Payment</td>
                                            <td v-else-if="inward_outward.system_module_id == '7'">Commission</td>
                                            <td v-else-if="inward_outward.system_module_id == '8'">Enquiry</td>
                                            <td v-else-if="inward_outward.system_module_id == '9'">Order</td>
                                            <td v-else-if="inward_outward.system_module_id == '10'">Complain</td>
                                            <td v-else-if="inward_outward.system_module_id == '11'">General</td>
                                            <td v-else>-</td>
                                            <td>{{ inward_outward.type_of_inward }}</td>
                                            <td>{{ inward_outward.followup_via }}</td>
                                            <td>{{inward_outward.subject}}</td>
                                            <td>{{ inward_outward.company_name }}</td>
                                            <td>{{ inward_outward.username }}</td>
                                            <td>{{ inward_outward.assigned_to }}</td>
                                        </tr>
                                        <tr v-else>
                                            <td>-</td>
                                            <td>{{inward_outward.ouid}}</td>
                                            <td>{{ inward_outward.selection_date }}</td>
                                            <td>-</td>
                                            <td>{{ inward_outward.type_of_outward }}</td>
                                            <td>{{ inward_outward.followup_via }}</td>
                                            <td>{{inward_outward.subject}}</td>
                                            <td>{{ inward_outward.company_name }}</td>
                                            <td>{{ inward_outward.username }}</td>
                                            <td>{{ inward_outward.assigned_to }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div><!-- .card -->
                        </div>
                    </div><!-- .nk-block -->
                </div>
            </div>
        </div>
    </div>


</template>

<script>
var references = [];
    export default {
        name: 'createCompany',
        props: {
            id: Number,
        },
        data() {
            return {
                referenceID: [],
                user: [],
                company: [],
                inward_outward: [],
            }
        },
        created() {
        },
        methods: {
            getProfilePic(name){
                return '/upload/company/multipleAddressProfilePic/' + name;
            },
        },
        mounted() {
            axios.get(`/reference/fetch-reference/${this.id}`)
            .then(response => {
                references = response.data;

                this.referenceID = references.Reference;
                this.user = references.User;
                this.company = references.Company;
                this.inward_outward = references.inward_outward;
            });
            console.log("This is about component");
        },
    };

</script>
